### ISSUE TITLE
Horizontal wind:  I thought the names were  bit indirect.  Why not either  u_wind and v_wind, or U and V, or zonal_wind and horizontal_wind?  I could think of many names, but yours were not ones I would have come up with

### ISSUE THREAD

**Issue by bjorn-stevens** [Geet-George/JOANNE#15]
**What is the issue you are facing? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Geet-George** [comment]
Done! I don't know how that slipped through. It should have been u_wind and v_wind.
