### ISSUE TITLE
FeatureType: coordinates

### ISSUE THREAD

**Issue by observingClouds** [Geet-George/JOANNE#22]
The `coordinates` parameter in the netCDF files of at least level 3 data contains `latitude` and `longitude`, however, the variables are called `lat` and `lon`. For the featureType `trajectory` to work, one or the other need to be changed.

**Comment by Geet-George** [comment]
Correct. I forgot to change the coordinates when I changed the var names.

**Comment by Geet-George** [comment]
Corrected from v0.7.0 onward
