### ISSUE TITLE
[directional wind]: wind direction and wind speed not recomputed from components after interpolation 

### ISSUE THREAD

**Issue by observingClouds** [Geet-George/JOANNE#25]
In the level 3 dataset the wind speed and wind direction that are measured are converted to the components `u` and `v` and afterwards interpolated. However, the `w_spd` and `w_dir` are not recomputed from the components and are thus erroneous.

I think the simple computation of `w_spd` and `w_dir` from the components has just been forgotten.

**Comment by Geet-George** [comment]
It works now. :) Quick look for a random sounding... 
![test_wdir_s0](https://user-images.githubusercontent.com/46085279/99034715-1bf3c680-257e-11eb-9485-8d8fe83c4006.png)

**Comment by observingClouds** [comment]
Great!
