### ISSUE TITLE
[ISSUE]: Compression by gathering possible? 

### ISSUE THREAD

**Issue by Geet-George** [Geet-George/JOANNE#38]
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#compression-by-gathering

Thanks to @d70-t for the suggestion.

**Comment by Geet-George** [comment]
Additionally, if [collection of features](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#representations-features) can be better represented?? Also suggested by @d70-t

**Comment by d70-t** [comment]
So my idea here was if the association of sondes <-> circles cloud be represented by one of these concepts. But probably both of these ideas only represent 1:n relations (I didn't fully check this). If that is the case, there could only be one circle per sonde (but multiple sondes per circle). But for JOANNE, there is also the need for multiple circles per sonde, so a n:m relation. So maybe the concepts are not applicable.
