### ISSUE TITLE
[alt coordinate]: missing `long_name` and `units` attribute

### ISSUE THREAD

**Issue by tmieslinger** [Geet-George/JOANNE#40]
Hi, I was wondering whether the `alt` coordinate could get a `long_name` and `units` attribute in JOANNE level 3 data (or is it there and it got lost somewhere in my own data handling?) It would be nice to have those for plotting the data :)

**Comment by Geet-George** [comment]
Hey, thanks. I just noticed it when you pointed this out. Will fix it!
