### ISSUE TITLE
[bug]: wrong axis attribute in Level 2 Data

### ISSUE THREAD

**Issue by d70-t** [Geet-George/JOANNE#50]
In JOANNE v0.9.2 level2 data, the `axis` attribute of the `lat` variable is "X" and the one of the `lon` variable is "Y". However, the CF conventions state:

In [4.1](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#latitude-coordinate):
> Optionally, the latitude type may be indicated additionally by providing the `standard_name` attribute with the value `latitude`, and/or the axis attribute with the value `Y`.

In [4.2](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#longitude-coordinate):
> Optionally, the longitude type may be indicated additionally by providing the `standard_name` attribute with the value `longitude`, and/or the axis attribute with the value `X`.

**Comment by Geet-George** [comment]
Thanks for pointing it out. I am always surprised by how many silly bugs keep coming up. I like that CF points out either of `standard_name` or `axis` is enough. Fewer chances of making errors like this.
