### ISSUE TITLE
int64 datatypes

### ISSUE THREAD

**Issue by d70-t** [Geet-George/JOANNE#52]
Int64 datatypes are incompatible with OPeNDAP and should be avoided. [Here](https://eurec4a.pages.gwdg.de/how_to_eurec4a/netcdf_datatypes.html) is some more explanation on this topic.

Also in `v0.9.2`, L3 the `alt` variable is an `int64` which is unexpected for an altitude variable.

**Comment by Geet-George** [comment]
Didn't know that! Thanks a lot for the write-up. Clears up a lot of things...
